name: test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        go-version: [1.21.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: ./.github/actions/install-node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run frontend checks
        run: make frontend-check

      - name: Run backend linter
        uses: golangci/golangci-lint-action@v3.7.0

      - name: Run backend format
        run: make backend-format

      - name: Run backend vet
        run: make backend-vet

      - name: Build
        run: make all

  unit-test-backend:
    name: Run backend unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_G_MAPS_API_KEY: ${{ secrets.G_MAPS_API_KEY }}

      - name: Run unit tests
        run: make backend-unit-test

  e2e-test-backend:
    name: Run backend end-to-end tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_G_MAPS_API_KEY: ${{ secrets.G_MAPS_API_KEY }}

      - name: Run end-to-end tests
        run: make backend-e2e-test
